inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'config.ru'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - '.git/**/*'

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: 'indented'

Style/WordArray:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Layout/LineLength:
  Exclude:
    - 'lib/modules/**/*'
    - 'lib/app/helpers/browser_logic.rb'

# Use code climate's metrics measurement rather than rubocop's
Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false
