# Name of app
app_name: Inferno

# Base path of application
# There are a few exceptions, such as "/" and "/landing".
base_path: "inferno"

# Useful during development to purge the database on each reload
purge_database_on_reload: false

# Disable peer SSL verification for environments that use SSL inspection
disable_verify_peer: false

# When running in a docker container, we have to listen to other than just 'localhost' which is the default
bind: '0.0.0.0'

# Omit TLS tests
disable_tls_tests: false

# Default scopes
default_scopes: launch launch/patient offline_access openid profile user/*.* patient/*.*

# Log Level: unkown, fatal, error, warn, info, debug
log_level: info

# Log to file
log_to_file: false

# Logging enabled?
logging_enabled: true

# Automatically Run Conformance Sequence on new server create
autorun_capability: false

# Include extra tests: true or false
include_extras: true

badge_text: Program Edition

# Resource validator options: must be one of "internal" or "external". external_resource_validator_url is only used if resource_validator is set to external.
resource_validator: internal
external_resource_validator_url: http://localhost:8081

# module options: one or more must be set.  The first option in the list will be checked by default
modules:
  - onc_certification

# preset fhir servers: optional. Minimally requires name, uri, module, optional inferno_uri, client_id, client_secret, scopes, instructions link
presets:
  reference_server:
    name: FHIR Reference Server
    uri: http://localhost:8080/r4
    module: onc_certification
    inferno_uri: http://localhost:4567
    client_id: SAMPLE_CONFIDENTIAL_CLIENT_ID
    confidential_client: true
    client_secret: SAMPLE_CONFIDENTIAL_CLIENT_SECRET
  cerner:
    name: Cerner
    uri: https://fhir-ehr.sandboxcerner.com/r4/0b8a0111-e8e6-4c26-a91c-5069cbc6b1ca
    module: onc_certification
    inferno_uri: http://localhost:4567
    client_id: a710f7e1-9e4b-4518-b5ba-69d0a25caebe
    confidential_client: false
    instructions: |
      To login for EHR launch https://cernercare.com/accounts/login Login/Password: smacvicar@mitre.org/TUAuAJnDyen59dn-
      You must use scopes: launch online_access openid profile patient/AllergyIntolerance.read patient/Condition.read patient/DocumentReference.read patient/Device.read patient/Encounter.read patient/Immunization.read patient/Organization.read patient/MedicationRequest.read patient/Patient.read patient/Procedure.read user/Practitioner.read
      ehr launch only, go to https://code.cerner.com/developer/smart-on-fhir/apps after logging in
      use portal/portal for user login
  care_evolution:
    name: Care Evolution
    uri: https://fhir.careevolution.com/Master.Adapter1.WebClient/api/fhir-r4
    client_id: 55990bf8-d85f-4a60-84b3-4699d1892f58
    confidential_client: true
    client_secret: secret
    instructions: |
      https://fhir.careevolution.com/Master.Adapter1.WebClient/fhir?prefix=fhir-r4
      click on 'smart clients can be registered here'
      user: rscanlon@mitre.org/InfernoInferno1
      only patient launch supported?
      use scope launch/patient patient/*.*
