# Name of app
app_name: Inferno

# Base path of application
# There are a few exceptions, such as "/" and "/landing".
base_path: "inferno"

# Useful during development to purge the database on each reload
purge_database_on_reload: false

# Disable peer SSL verification for environments that use SSL inspection
disable_verify_peer: false

# When running in a docker container, we have to listen to other than just 'localhost' which is the default
bind: '0.0.0.0'

# Omit TLS tests
disable_tls_tests: false

# Default scopes
default_scopes: launch launch/patient offline_access openid profile user/*.* patient/*.*

# Log Level: unkown, fatal, error, warn, info, debug
log_level: info

# Log to file
log_to_file: false

# Logging enabled?
logging_enabled: true

# Automatically Run Conformance Sequence on new server create
autorun_capability: false

# Include extra tests: true or false
include_extras: true

badge_text: Program Edition

# module options: one or more must be set.  The first option in the list will be checked by default
modules:
  - onc_certification

# preset fhir servers: optional. Minimally requires name, uri, module, optional inferno_uri, client_id, client_secret, scopes, instructions link
presets:
  refernce_server: 
    name: FHIR Reference Server
    uri: http://localhost:8080/r4
    module: onc_certification
    inferno_uri: http://localhost:4567
    client_id: SAMPLE_CONFIDENTIAL_CLIENT_ID
    confidential_client: true
    client_secret: SAMPLE_CONFIDENTIAL_CLIENT_SECRET