version: '3.2'
services:
  ruby_server:
    build:
      context: .
      dockerfile: terminology_dockerfile
    volumes:
      - type: bind
        source: "./resources/terminology/validators"
        target: "/var/www/inferno/resources/terminology/validators"
        consistency: delegated
      - type: bind
        source: "./tmp"
        target: "/var/www/inferno/tmp"
        consistency: delegated
    environment:
      UMLS_USERNAME:
      UMLS_PASSWORD:
